### ISSUE TITLE
Datepicker not working

### ISSUE THREAD

**Issue by SamiAssasi** [inviqa/mx-widgetcomponent#22]
Hi guys,

Having this problem when trying to add the datepicker or datepickertime to widget.xml

"Only 'data' node can be child of 'block' node, #comment found";i:1;s:11425:"#0"

**Comment by tkotosz** [comment]
did you use this format? https://github.com/inviqa/mx-widgetcomponent#date-picker-1

**Comment by SamiAssasi** [comment]
Yess, I got it working now. Just a question, I changed the dateformat to d-m-Y and I can add the date correctly to the widget, but when I edit it the month is always 0.

So if I set the date as 3rd of November (3-11-2017) and insert the widget, when I edit it shows as (3-0-2017)

**Comment by tkotosz** [comment]
@SamiAssasi Hi, Sorry I didn't notice your comment. As far as I know Magento2 uses the IntlDateFormatter, where "m" is the minute. So you need to use "d-M-Y" to get "3-11-2017". (see http://userguide.icu-project.org/formatparse/datetime). This is my guess.

**Comment by tkotosz** [comment]
This issue should be fixed in https://github.com/inviqa/mx-widgetcomponent/releases/tag/v2.2.1
